services:
  - type: web
    name: nim-proxy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: NIM_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0